// Simple synchronous JSON settings store (replaces electron-store)
import { readFileSync, writeFileSync, mkdirSync, existsSync, renameSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import type { NohiSettings } from './engine/types'
import { log, logError } from './engine/lib/logger'

const CONFIG_DIR = join(homedir(), '.nohi')
const CONFIG_FILE = join(CONFIG_DIR, 'settings.json')

const DEFAULTS: NohiSettings = {
  defaultModel: 'claude-sonnet-4-6',
  primaryProvider: 'anthropic' as const,
  skillsDir: join(homedir(), '.nohi', 'skills'),
  workingDir: homedir(),
  mcpServers: [],
  theme: 'light',
  language: 'en',
  autoSyncCatalog: false,
  autoPushChannels: false,
  autoGenerateDescriptions: true,
  autoUpdateBrandContext: false,
  notifyDesktop: true,
  notifyChannelSync: true,
}

function ensureDir(): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true })
  }
}

/** Returns true if a string looks like a plausible API key (not a URL or placeholder) */
function isValidApiKey(v: unknown): boolean {
  if (typeof v !== 'string' || !v.trim()) return false
  const s = v.trim()
  // Reject explicit URLs (http/https scheme, or host.tld/path pattern)
  if (s.startsWith('http://') || s.startsWith('https://')) return false
  if (s.includes('://')) return false
  // Reject values that look like domain paths, e.g. "linkedin.com/in/foo"
  if (/^[a-z0-9-]+\.[a-z]{2,}\//.test(s)) return false
  // Must be at least 20 chars to be a real key
  if (s.length < 20) return false
  return true
}

export function getSettings(): NohiSettings {
  ensureDir()
  try {
    if (existsSync(CONFIG_FILE)) {
      const raw = readFileSync(CONFIG_FILE, 'utf-8')
      const parsed = JSON.parse(raw)
      // Auto-detect primaryProvider: if set provider has no key, pick first provider that does
      const providerKeyMap: Record<string, string> = {
        anthropic: 'anthropicApiKey',
        openai: 'openaiApiKey',
        kimi: 'kimiApiKey',
        minimax: 'minimaxApiKey',
        deepseek: 'deepseekApiKey',
      }
      const currentProvider = parsed.primaryProvider || DEFAULTS.primaryProvider
      const currentKeyField = providerKeyMap[currentProvider]
      if (!currentKeyField || !parsed[currentKeyField]) {
        // Current provider has no key — find one that does
        const available = Object.entries(providerKeyMap).find(
          ([, keyField]) => parsed[keyField] && isValidApiKey(parsed[keyField])
        )
        parsed.primaryProvider = available ? available[0] : currentProvider
      } else {
        parsed.primaryProvider = currentProvider
      }
      // Ensure defaultModel matches the provider if it's mismatched
      const providerDefaultModels: Record<string, string> = {
        anthropic: 'claude-sonnet-4-6',
        openai: 'gpt-4o',
        kimi: 'moonshot-v1-8k',
        minimax: 'abab6.5s-chat',
        deepseek: 'deepseek-chat',
      }
      const expectedPrefix: Record<string, string[]> = {
        anthropic: ['claude'],
        openai: ['gpt-', 'o1', 'o3', 'o4'],
        kimi: ['moonshot'],
        minimax: ['abab'],
        deepseek: ['deepseek'],
      }
      const prefixes = expectedPrefix[parsed.primaryProvider] ?? []
      const modelMatchesProvider = prefixes.some((p: string) => (parsed.defaultModel ?? '').includes(p))
      if (!modelMatchesProvider) {
        parsed.defaultModel = providerDefaultModels[parsed.primaryProvider] ?? DEFAULTS.defaultModel
      }
      // Strip any API keys that look like URLs or invalid values
      const API_KEY_FIELDS = [
        'anthropicApiKey', 'openaiApiKey', 'kimiApiKey', 'minimaxApiKey', 'deepseekApiKey',
      ] as const
      for (const field of API_KEY_FIELDS) {
        if (parsed[field] !== undefined && !isValidApiKey(parsed[field])) {
          delete parsed[field]
        }
      }
      // Remove empty-string fields so DEFAULTS fill them properly
      for (const key of ['workingDir', 'skillsDir'] as const) {
        if (parsed[key] === '') delete parsed[key]
      }
      return { ...DEFAULTS, ...parsed }
    }
  } catch (err) {
    logError(err, '[store] settings.json corrupt — falling back to defaults')
  }
  return { ...DEFAULTS }
}

// Last save error — exposed via IPC so the renderer can show a toast.
let lastSaveError: { message: string; timestamp: number; path: string } | null = null

export function getLastSettingsError(): { message: string; timestamp: number; path: string } | null {
  return lastSaveError
}

/** Save settings atomically (temp file + rename). Throws on failure so callers can react. */
export function saveSettings(settings: NohiSettings): void {
  try {
    ensureDir()
    const json = JSON.stringify(settings, null, 2)
    // Atomic write: write to temp, then rename. Avoids half-written settings on crash.
    const tmp = `${CONFIG_FILE}.tmp.${process.pid}`
    writeFileSync(tmp, json, 'utf-8')
    renameSync(tmp, CONFIG_FILE)
    lastSaveError = null
    log('debug', '[store] settings saved')
  } catch (err) {
    const e = err as { code?: string; message?: string }
    lastSaveError = {
      message: e.code === 'EACCES'
        ? `Cannot write settings — ~/.nohi/ is not writable. Check permissions on ${CONFIG_DIR}.`
        : e.code === 'ENOSPC'
          ? 'Cannot write settings — disk is full.'
          : e.code === 'EROFS'
            ? `Cannot write settings — ~/.nohi/ is on a read-only filesystem.`
            : `Failed to save settings: ${e.message ?? String(err)}`,
      timestamp: Date.now(),
      path: CONFIG_FILE,
    }
    logError(err, '[store] saveSettings failed')
    throw err
  }
}
