// Simple synchronous JSON settings store (replaces electron-store)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import type { NohiSettings } from './engine/types'

const CONFIG_DIR = join(homedir(), '.nohi')
const CONFIG_FILE = join(CONFIG_DIR, 'settings.json')

const DEFAULTS: NohiSettings = {
  defaultModel: 'claude-sonnet-4-6',
  primaryProvider: 'anthropic',
  skillsDir: join(homedir(), '.nohi', 'skills'),
  workingDir: homedir(),
  mcpServers: [],
  theme: 'light',
  language: 'en',
  autoSyncCatalog: false,
  autoPushChannels: false,
  autoGenerateDescriptions: true,
  autoUpdateBrandContext: false,
  notifyDesktop: true,
  notifyChannelSync: true,
}

function ensureDir(): void {
  if (!existsSync(CONFIG_DIR)) {
    mkdirSync(CONFIG_DIR, { recursive: true })
  }
}

export function getSettings(): NohiSettings {
  ensureDir()
  try {
    if (existsSync(CONFIG_FILE)) {
      const raw = readFileSync(CONFIG_FILE, 'utf-8')
      return { ...DEFAULTS, ...JSON.parse(raw) }
    }
  } catch {
    // Corrupt config — use defaults
  }
  return { ...DEFAULTS }
}

export function saveSettings(settings: NohiSettings): void {
  ensureDir()
  writeFileSync(CONFIG_FILE, JSON.stringify(settings, null, 2), 'utf-8')
}
