// Namespaced read-only view over NohiSettings.
// Phase 2D: Rather than force a one-shot migration across ~50 read sites,
// we expose a `settingsView()` helper that organizes the flat settings
// object into the logical groups defined in the PRD. New code uses the view;
// old code keeps working on the flat shape. Full cutover deferred to a
// future release when the risk/reward is favorable.

import type { NohiSettings } from '../types'

export interface SettingsView {
  providers: {
    anthropic?: string
    openai?: string
    kimi?: string
    minimax?: string
    deepseek?: string
    google?: string
    primary?: NohiSettings['primaryProvider']
    defaultModel: string
  }
  app: {
    skillsDir: string
    workingDir: string
    theme: 'light' | 'dark'
    language?: 'en' | 'zh'
    whisperBinPath?: string
  }
  store: {
    name?: string
    url?: string
    category?: string
    gmvRange?: string
    teamSize?: string
  }
  features: {
    autoSyncCatalog?: boolean
    autoPushChannels?: boolean
    autoGenerateDescriptions?: boolean
    autoUpdateBrandContext?: boolean
  }
  notifications: {
    desktop?: boolean
    costThreshold?: number
    channelSync?: boolean
  }
  integrations: {
    brave?: { apiKey?: string }
    firecrawl?: { apiKey?: string; apiUrl?: string }
    catalog: { apiUrl?: string; apiToken?: string; merchantId?: string }
  }
  mcp: {
    servers: NohiSettings['mcpServers']
  }
  hooks: NohiSettings['hooks']
  skills: {
    enabledIds?: string[]
  }
}

/** Build a namespaced view of the current settings. Pure — no I/O, just reshaping. */
export function settingsView(s: NohiSettings): SettingsView {
  return {
    providers: {
      anthropic: s.anthropicApiKey,
      openai: s.openaiApiKey,
      kimi: s.kimiApiKey,
      minimax: s.minimaxApiKey,
      deepseek: s.deepseekApiKey,
      google: s.googleApiKey,
      primary: s.primaryProvider,
      defaultModel: s.defaultModel,
    },
    app: {
      skillsDir: s.skillsDir,
      workingDir: s.workingDir,
      theme: s.theme,
      language: s.language,
      whisperBinPath: s.whisperBinPath,
    },
    store: {
      name: s.storeName,
      url: s.storeUrl,
      category: s.storeCategory,
      gmvRange: s.storeGmvRange,
      teamSize: s.teamSize,
    },
    features: {
      autoSyncCatalog: s.autoSyncCatalog,
      autoPushChannels: s.autoPushChannels,
      autoGenerateDescriptions: s.autoGenerateDescriptions,
      autoUpdateBrandContext: s.autoUpdateBrandContext,
    },
    notifications: {
      desktop: s.notifyDesktop,
      costThreshold: s.notifyCostThreshold,
      channelSync: s.notifyChannelSync,
    },
    integrations: {
      brave: s.braveSearchApiKey ? { apiKey: s.braveSearchApiKey } : undefined,
      firecrawl: (s.firecrawlApiKey || s.firecrawlApiUrl)
        ? { apiKey: s.firecrawlApiKey, apiUrl: s.firecrawlApiUrl }
        : undefined,
      catalog: {
        apiUrl: s.catalogApiUrl,
        apiToken: s.catalogApiToken,
        merchantId: s.merchantId,
      },
    },
    mcp: { servers: s.mcpServers },
    hooks: s.hooks,
    skills: { enabledIds: s.enabledSkillIds },
  }
}

/** Shortcut to grab just the integrations subtree (the most-used in tools). */
export function integrationsView(s: NohiSettings): SettingsView['integrations'] {
  return settingsView(s).integrations
}
