// Runtime validation schemas for IPC inputs.
// These guard the boundary between renderer (untrusted) and main (trusted).
// Use `Schema.parse()` at the start of every ipcMain.handle handler.

import { z } from 'zod'

// ─── Sessions ──────────────────────────────────────────────────────────────

export const SessionMessageSchema = z.object({
  id: z.string().min(1).max(200),
  role: z.enum(['user', 'assistant']),
  // Content is either a string or an array of content blocks; both allowed shapes are loose
  content: z.union([z.string(), z.array(z.unknown())]),
  timestamp: z.number(),
})

export const SessionSchema = z.object({
  id: z.string().min(1).max(200),
  title: z.string().max(500).default('New conversation'),
  createdAt: z.number(),
  updatedAt: z.number(),
  messages: z.array(SessionMessageSchema),
  model: z.string().min(1).max(100),
  workingDir: z.string().max(2000),
  planMode: z.boolean().optional(),
})

export const CreateSessionSchema = z.object({
  model: z.string().min(1).max(100),
  workingDir: z.string().max(2000).optional(),
})

// ─── Skills ────────────────────────────────────────────────────────────────

export const SkillCreateSchema = z.object({
  name: z.string().min(1).max(100).regex(/^[a-z0-9-]+$/i, 'Skill name must be alphanumeric with dashes'),
  description: z.string().min(1).max(500),
  trigger: z.string().min(1).max(500),
  content: z.string().min(1).max(50_000),
})

export const SkillUpdateSchema = SkillCreateSchema.extend({
  id: z.string().min(1).max(200),
})

// ─── Settings ──────────────────────────────────────────────────────────────

export const NohiSettingsSchema = z.object({
  anthropicApiKey: z.string().max(500).optional(),
  openaiApiKey: z.string().max(500).optional(),
  googleApiKey: z.string().max(500).optional(),
  kimiApiKey: z.string().max(500).optional(),
  minimaxApiKey: z.string().max(500).optional(),
  deepseekApiKey: z.string().max(500).optional(),
  primaryProvider: z.enum(['anthropic', 'openai', 'kimi', 'minimax', 'deepseek']).optional(),
  defaultModel: z.string().min(1).max(100),
  skillsDir: z.string().max(2000),
  workingDir: z.string().max(2000),
  mcpServers: z.array(z.object({
    id: z.string().max(200),
    name: z.string().max(200),
    command: z.string().max(2000),
    args: z.array(z.string().max(2000)),
    env: z.record(z.string(), z.string().max(2000)).optional(),
    enabled: z.boolean(),
  })),
  theme: z.enum(['dark', 'light']),
  language: z.enum(['en', 'zh']).optional(),
  storeName: z.string().max(200).optional(),
  storeUrl: z.string().max(500).optional(),
  storeCategory: z.string().max(200).optional(),
  storeGmvRange: z.string().max(50).optional(),
  teamSize: z.string().max(50).optional(),
  autoSyncCatalog: z.boolean().optional(),
  autoPushChannels: z.boolean().optional(),
  autoGenerateDescriptions: z.boolean().optional(),
  autoUpdateBrandContext: z.boolean().optional(),
  notifyDesktop: z.boolean().optional(),
  notifyCostThreshold: z.number().optional(),
  notifyChannelSync: z.boolean().optional(),
  enabledSkillIds: z.array(z.string()).optional(),
  whisperBinPath: z.string().max(2000).optional(),
  braveSearchApiKey: z.string().max(500).optional(),
  firecrawlApiKey: z.string().max(500).optional(),
  firecrawlApiUrl: z.string().max(2000).optional(),
  catalogApiUrl: z.string().max(2000).optional(),
  catalogApiToken: z.string().max(500).optional(),
  merchantId: z.string().max(200).optional(),
  hooks: z.array(z.object({
    event: z.enum(['PreToolUse', 'PostToolUse', 'Stop', 'UserPromptSubmit']),
    matcher: z.string().max(200).optional(),
    command: z.string().min(1).max(10_000),
    description: z.string().max(500).optional(),
    enabled: z.boolean().optional(),
  })).optional(),
  telemetryEnabled: z.boolean().optional(),
  bashConsentMode: z.enum(['off', 'dangerous', 'always', 'allowlist']).optional(),
  bashAllowlist: z.array(z.string().max(500)).max(200).optional(),
  migratedPlaintextKeys: z.boolean().optional(),
})

// ─── Automation ────────────────────────────────────────────────────────────

export const AutomationCreateSchema = z.object({
  name: z.string().min(1).max(200),
  description: z.string().max(500).optional(),
  prompt: z.string().min(1).max(20_000),
  schedule: z.enum(['manual', 'hourly', 'daily', 'weekly']),
  timeOfDay: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, 'timeOfDay must be HH:mm in 24-hour format').optional(),
  dayOfWeek: z.number().int().min(0).max(6).optional(),
  model: z.string().max(100).optional(),
})

export const AutomationUpdateSchema = AutomationCreateSchema.partial().extend({
  status: z.enum(['active', 'paused']).optional(),
})

// ─── Helper: parse with friendly error ─────────────────────────────────────

export function safeParseIpc<T>(schema: z.ZodSchema<T>, input: unknown, label: string): T {
  const result = schema.safeParse(input)
  if (!result.success) {
    const issues = result.error.issues
      .slice(0, 3)
      .map((i) => `${i.path.join('.') || 'root'}: ${i.message}`)
      .join('; ')
    throw new Error(`[IPC ${label}] Invalid input — ${issues}`)
  }
  return result.data
}
