// ─── Core types for Nohi Central PRO engine ───────────────────────────────

export type Role = 'user' | 'assistant'

export interface TextBlock {
  type: 'text'
  text: string
}

export interface ToolUseBlock {
  type: 'tool_use'
  id: string
  name: string
  input: Record<string, unknown>
}

export interface ToolResultBlock {
  type: 'tool_result'
  tool_use_id: string
  content: string | ContentBlock[]
  is_error?: boolean
}

export type ContentBlock = TextBlock | ToolUseBlock | ToolResultBlock

export interface Message {
  role: Role
  content: string | ContentBlock[]
}

// ─── Tool interface ────────────────────────────────────────────────────────

export interface ToolResult {
  output?: string
  error?: string
  interrupted?: boolean
}

export interface ToolDef {
  name: string
  description: string
  inputSchema: Record<string, unknown>
  call(input: Record<string, unknown>, opts: ToolCallOpts): Promise<ToolResult>
}

export interface ToolCallOpts {
  workingDir: string
  onProgress?: (text: string) => void
  settings?: NohiSettings
}

// ─── Streaming events (sent to renderer via IPC) ──────────────────────────

export type AgentEvent =
  | { type: 'text_delta'; delta: string }
  | { type: 'thinking_delta'; delta: string }
  | { type: 'tool_start'; id: string; name: string; input: Record<string, unknown> }
  | { type: 'tool_result'; id: string; name: string; output: string; isError: boolean }
  | { type: 'todos_updated'; todos: Array<{ content: string; activeForm: string; status: 'pending' | 'in_progress' | 'completed' }> }
  | { type: 'message_complete'; usage: { input_tokens: number; output_tokens: number } }
  | { type: 'error'; message: string }
  | { type: 'done' }

// ─── Session types ─────────────────────────────────────────────────────────

export interface SessionMessage {
  id: string
  role: Role
  content: string | ContentBlock[]
  timestamp: number
}

export interface Session {
  id: string
  title: string
  createdAt: number
  updatedAt: number
  messages: SessionMessage[]
  model: string
  workingDir: string
  planMode?: boolean
}

// ─── Settings ─────────────────────────────────────────────────────────────

export interface NohiSettings {
  // AI provider keys
  anthropicApiKey?: string
  openaiApiKey?: string
  googleApiKey?: string
  kimiApiKey?: string
  minimaxApiKey?: string
  deepseekApiKey?: string
  // Active provider + model
  primaryProvider?: 'anthropic' | 'openai' | 'kimi' | 'minimax' | 'deepseek'
  defaultModel: string
  // App config
  skillsDir: string
  workingDir: string
  mcpServers: McpServerConfig[]
  theme: 'dark' | 'light'
  language?: 'en' | 'zh'
  // Store info
  storeName?: string
  storeUrl?: string
  storeCategory?: string
  storeGmvRange?: string
  teamSize?: string
  // Permissions
  autoSyncCatalog?: boolean
  autoPushChannels?: boolean
  autoGenerateDescriptions?: boolean
  autoUpdateBrandContext?: boolean
  // Notifications
  notifyDesktop?: boolean
  notifyCostThreshold?: number
  notifyChannelSync?: boolean
  // Skill toggle state — IDs of skills that are enabled
  enabledSkillIds?: string[]
  // Voice transcription binary (overrides default whisper-cli path)
  whisperBinPath?: string
  // Brave Search API key for web search tool
  braveSearchApiKey?: string
  // Firecrawl API key for advanced web scraping/crawling
  firecrawlApiKey?: string
  // Optional self-hosted Firecrawl instance URL (defaults to https://api.firecrawl.dev)
  firecrawlApiUrl?: string
  // Agentic Catalog configuration
  catalogApiUrl?: string
  catalogApiToken?: string
  merchantId?: string
  // Lifecycle hooks (PreToolUse / PostToolUse / Stop / UserPromptSubmit)
  hooks?: HookConfig[]
  // Local-only telemetry (opt-in). Writes to ~/.nohi/telemetry/<YYYY-MM>.jsonl.
  // Nothing is uploaded — purely a local record the user can inspect.
  telemetryEnabled?: boolean
}

export interface HookConfig {
  event: 'PreToolUse' | 'PostToolUse' | 'Stop' | 'UserPromptSubmit'
  matcher?: string
  command: string
  description?: string
  enabled?: boolean
}

export interface McpServerConfig {
  id: string
  name: string
  command: string
  args: string[]
  env?: Record<string, string>
  enabled: boolean
}

// ─── Skill types ───────────────────────────────────────────────────────────

export interface Skill {
  id: string
  name: string
  description: string
  trigger: string
  content: string
  source: 'builtin' | 'custom'
  enabled: boolean
  filePath?: string
}
